// AUTO-GENERATED by scripts/generate-sprites.ts — do not edit by hand.
// Run `npm run generate:sprites` to regenerate.

export type ManifestEntry = {
  readonly bbox: { readonly x: number; readonly y: number; readonly w: number; readonly h: number };
  readonly cx: number;
  readonly cy: number;
};

export const SPRITE_MANIFEST: Readonly<Record<string, ManifestEntry>> = Object.freeze({
  ab_corrosive: { bbox: { x: 0, y: 0, w: 200, h: 245 }, cx: 100, cy: 122.5 },
  ab_voltaic: { bbox: { x: 16, y: 22, w: 168, h: 231 }, cx: 100, cy: 137.5 },
  app_lash: { bbox: { x: 34, y: 44, w: 143, h: 179 }, cx: 105.5, cy: 133.5 },
  app_spinneret: { bbox: { x: 33, y: 66, w: 136, h: 130 }, cx: 101, cy: 131 },
  app_stinger: { bbox: { x: 10, y: 12, w: 174, h: 233 }, cx: 97, cy: 128.5 },
  cara_bare: { bbox: { x: 25, y: 44, w: 137, h: 168 }, cx: 93.5, cy: 128 },
  cara_bone: { bbox: { x: 14, y: 35, w: 159, h: 202 }, cx: 93.5, cy: 136 },
  cara_chitin: { bbox: { x: 25, y: 24, w: 150, h: 226 }, cx: 100, cy: 137 },
  cara_hide: { bbox: { x: 17, y: 48, w: 156, h: 176 }, cx: 95, cy: 136 },
  eyes_bright: { bbox: { x: 17, y: 65, w: 167, h: 62 }, cx: 100.5, cy: 96 },
  eyes_multi: { bbox: { x: 23, y: 72, w: 154, h: 98 }, cx: 100, cy: 121 },
  eyes_plain: { bbox: { x: 25, y: 106, w: 150, h: 38 }, cx: 100, cy: 125 },
  eyes_singular: { bbox: { x: 21, y: 46, w: 158, h: 124 }, cx: 100, cy: 108 },
  head_folded: { bbox: { x: 44, y: 44, w: 110, h: 139 }, cx: 99, cy: 113.5 },
  head_mandible: { bbox: { x: 47, y: 44, w: 128, h: 117 }, cx: 111, cy: 102.5 },
  head_maw: { bbox: { x: 46, y: 44, w: 101, h: 115 }, cx: 96.5, cy: 101.5 },
  head_plain: { bbox: { x: 44, y: 44, w: 112, h: 115 }, cx: 100, cy: 101.5 },
  head_sensor: { bbox: { x: 44, y: 24, w: 112, h: 135 }, cx: 100, cy: 91.5 },
  hide_luminescent: { bbox: { x: 25, y: 23, w: 150, h: 234 }, cx: 100, cy: 140 },
  hide_spotted: { bbox: { x: 0, y: 0, w: 200, h: 272 }, cx: 100, cy: 136 },
  hide_striped: { bbox: { x: 40, y: 100, w: 121, h: 89 }, cx: 100.5, cy: 144.5 },
  loco_bulk: { bbox: { x: 0, y: 44, w: 200, h: 224 }, cx: 100, cy: 156 },
  loco_burrow: { bbox: { x: 8, y: 74, w: 192, h: 195 }, cx: 104, cy: 171.5 },
  loco_plain: { bbox: { x: 62, y: 82, w: 89, h: 198 }, cx: 106.5, cy: 181 },
  loco_sprint: { bbox: { x: 23, y: 76, w: 135, h: 201 }, cx: 90.5, cy: 176.5 },
});

export const INTENTIONALLY_EMPTY: ReadonlySet<string> = new Set(['app_none', 'hide_plain', 'ab_none']);
