/* eslint-disable no-console */
import { readdir, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import sharp from 'sharp';
import { computeBbox, remapPixel, type RGB } from './lib/sprite-image';
import { PALETTES } from '../src/sim/data/palettes';

const REPO = resolve(process.cwd());
const SRC_DIR = join(REPO, 'public/assets/pixellab/traits');
const OUT_DIR = join(REPO, 'public/assets/pixellab/traits-computed');
const MANIFEST_PATH = join(REPO, 'src/render/sprite-manifest.generated.ts');

const ALPHA_THRESHOLD = 32;

// Baked-in reference ramp (matches the palette given to PixelLab).
// Used by palette-remap steps (later tasks); kept here so it lives alongside
// the script that consumes it.
export const REF: readonly RGB[] = [
  [0x14, 0x28, 0x2a],
  [0x2f, 0x5a, 0x5a],
  [0x5f, 0x8f, 0x8f],
  [0x4d, 0xff, 0xb0],
];

// Three alleles are intentionally "no visible feature" — no source PNG on disk.
const INTENTIONALLY_EMPTY = new Set(['app_none', 'hide_plain', 'ab_none']);

export function hexToRgb(hex: string): RGB {
  const h = hex.replace('#', '');
  return [
    parseInt(h.slice(0, 2), 16),
    parseInt(h.slice(2, 4), 16),
    parseInt(h.slice(4, 6), 16),
  ];
}

async function listSourceAlleles(): Promise<string[]> {
  const files = await readdir(SRC_DIR);
  return files
    .filter((f: string) => f.endsWith('.png') && !f.startsWith('_'))
    .map((f: string) => f.replace(/\.png$/, ''))
    .sort();
}

async function main() {
  console.log(`Reading sources from ${SRC_DIR}`);
  const alleles = await listSourceAlleles();
  console.log(`Found ${alleles.length} source PNGs`);

  if (!existsSync(OUT_DIR)) await mkdir(OUT_DIR, { recursive: true });

  type ManifestEntry = { bbox: { x: number; y: number; w: number; h: number }; cx: number; cy: number };
  const manifest: Record<string, ManifestEntry> = {};

  for (const allele of alleles) {
    const src = join(SRC_DIR, `${allele}.png`);
    const raw = await sharp(src).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    const { width, height } = raw.info;
    const bb = computeBbox(raw.data, width, height, ALPHA_THRESHOLD);
    if (!bb) {
      console.warn(`  ${allele}: no opaque pixels above threshold — skipping`);
      continue;
    }
    manifest[allele] = { bbox: { x: bb.x, y: bb.y, w: bb.w, h: bb.h }, cx: bb.cx, cy: bb.cy };
    console.log(`  ${allele}: bbox=${bb.x},${bb.y} ${bb.w}x${bb.h} c=(${bb.cx},${bb.cy})`);
  }

  // Sanity: unknown palettes / empty palette set would silently produce zero variants.
  if (Object.keys(PALETTES).length === 0) throw new Error('PALETTES is empty');

  const paletteIds = Object.keys(PALETTES).sort();

  for (const allele of Object.keys(manifest)) {
    const src = join(SRC_DIR, `${allele}.png`);
    const raw = await sharp(src).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    const { width, height } = raw.info;

    for (const paletteId of paletteIds) {
      const palette = PALETTES[paletteId]!;
      const target: readonly RGB[] = palette.ramp.map(hexToRgb);
      const out = Buffer.from(raw.data); // copy source RGBA
      for (let i = 0; i < out.length; i += 4) {
        const a = out[i + 3]!;
        if (a < ALPHA_THRESHOLD) continue; // preserve near-transparent pixels
        const [nr, ng, nb] = remapPixel(out[i]!, out[i + 1]!, out[i + 2]!, REF, target);
        out[i] = nr; out[i + 1] = ng; out[i + 2] = nb;
      }
      const dst = join(OUT_DIR, `${allele}_${paletteId}.png`);
      await sharp(out, { raw: { width, height, channels: 4 } }).png().toFile(dst);
    }
    console.log(`  ${allele}: wrote ${paletteIds.length} palette variants`);
  }

  const source = renderManifestModule(manifest, INTENTIONALLY_EMPTY);
  await writeFile(MANIFEST_PATH, source, 'utf8');
  console.log(`Wrote ${MANIFEST_PATH} with ${Object.keys(manifest).length} entries`);
}

function renderManifestModule(
  manifest: Record<string, { bbox: { x: number; y: number; w: number; h: number }; cx: number; cy: number }>,
  intentionallyEmpty: ReadonlySet<string>,
): string {
  const header = [
    '// AUTO-GENERATED by scripts/generate-sprites.ts — do not edit by hand.',
    '// Run `npm run generate:sprites` to regenerate.',
    '',
    'export type ManifestEntry = {',
    '  readonly bbox: { readonly x: number; readonly y: number; readonly w: number; readonly h: number };',
    '  readonly cx: number;',
    '  readonly cy: number;',
    '};',
    '',
    'export const SPRITE_MANIFEST: Readonly<Record<string, ManifestEntry>> = Object.freeze({',
  ].join('\n');
  const rows = Object.keys(manifest).sort().map((k) => {
    const e = manifest[k]!;
    return `  ${k}: { bbox: { x: ${e.bbox.x}, y: ${e.bbox.y}, w: ${e.bbox.w}, h: ${e.bbox.h} }, cx: ${e.cx}, cy: ${e.cy} },`;
  }).join('\n');
  const footer = [
    '});',
    '',
    `export const INTENTIONALLY_EMPTY: ReadonlySet<string> = new Set([${[...intentionallyEmpty].map((s) => `'${s}'`).join(', ')}]);`,
    '',
  ].join('\n');
  return `${header}\n${rows}\n${footer}`;
}

await main();
